Traceback (most recent call last):
  File "C:\Users\USUARIO\anaconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\USUARIO\anaconda3\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USUARIO\anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USUARIO\anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\USUARIO\anaconda3\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\USUARIO\anaconda3\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\USUARIO\anaconda3\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Earth Engine
import ee
ee.Initialize()

import geemap
import geemap.colormaps as cmp # Paletas para visualizaciÃ³n de imÃ¡genes (cm se confunde con matplotlib)

import pandas as pd
from ipywidgets import interact, fixed
import os

import matplotlib.pyplot as plt

# Archivos .py con funciones
from vis_tools import *
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[2], line 2[0m
[0;32m      1[0m [38;5;66;03m# Earth Engine[39;00m
[1;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mee[39;00m
[0;32m      3[0m ee[38;5;241m.[39mInitialize()
[0;32m      5[0m [38;5;28;01mimport[39;00m [38;5;21;01mgeemap[39;00m

[1;31mModuleNotFoundError[0m: No module named 'ee'

